image: node:7-slim

pages:
  stage: deploy
  script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn
  - yarn run build
  - rm public/bundle.js.map
  artifacts:
    paths:
    - $CI_PROJECT_DIR/public
  only:
  - master
