import ILineData from "./linedata";

export const data: ILineData[] = [
    {
        id: "318",
        line: "L1",
        name: "kahrizak",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.521582",
        lon: "51.369265",
    },
    {
        id: "319",
        line: "L1",
        name: "haram-e motahar",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.545095",
        lon: "51.372992",
    },
    {
        id: "320",
        line: "L1",
        name: "shahed - bagher shahr",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.547053",
        lon: "51.382568",
    },
    {
        id: "321",
        line: "L1",
        name: "palayeshgah",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.559796",
        lon: "51.399475",
    },
    {
        id: "322",
        line: "L1",
        name: "shahr-e rey",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.594785",
        lon: "51.422345",
    },
    {
        id: "323",
        line: "L1",
        name: "javanmard-e ghasab",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.609965",
        lon: "51.419533",
    },
    {
        id: "324",
        line: "L1",
        name: "ali abad",
        accessibility: "Adaptada",
        zone: "Zona 1",
        connections: "",
        lat: "35.629598",
        lon: "51.415754",
    },
];  
